### PR TITLE
Release/0.3.4

### PR DESCRIPTION
**Pull request by tomwojcik**
Let's do this

### CODE REVIEW

**Comment by hhamana** [comment]
While I'm guessing the error handling refactor in https://github.com/tomwojcik/starlette-context/pull/59 can be for later, the original issue was some lack of feedback to see what could be the problem on an invalid header passed.
Maybe we can just add a simple logging there?

**Comment by hhamana** [comment]
We can probable deprecate the ContextMiddleware from 0.4, since it's a potential security issue when misused, no need to wait until everything is confirmed stable with 1.0.

**Comment by tomwojcik** [comment]
> While I'm guessing the error handling refactor in #59 can be for later, the original issue was some lack of feedback to see what could be the problem on an invalid header passed. Maybe we can just add a simple logging there?

There was no release for almost a year. I think we can push whatever it is that we have and handle this in the next patch version. 

> We can probable deprecate the ContextMiddleware from 0.4, since it's a potential security issue when misused, no need to wait until everything is confirmed stable with 1.0.

We could, but once we drop `ContextMiddleware`, we know the rest of the codebase is production-ready and stable, so there's no need to release it as minor (IMO). Also, we'd be able to chop the code in half + cleanup tests.

**Comment by hhamana** [comment]
> handle this in the next patch version.
that refactor is a breaking change too, so that'll have to be a minor at least.
the way I see it, if you want to release something now:
- 0.3.4: what we have
- 0.3.5: add that little bit of logging
- 0.4: remove ContextMiddleware, error response handling refactor
- if no further feedback after 0.4, make it 1.0

**Comment by tomwojcik** [comment]
> > handle this in the next patch version.
> 
> that refactor is a breaking change too, so that'll have to be a minor at least. the way I see it, if you want to release something now:
> 
> * 0.3.4: what we have
> * 0.3.5: add that little bit of logging
> * 0.4: remove ContextMiddleware, error response handling refactor
> * if no further feedback after 0.4, make it 1.0

ok

**Pull request merged**
