### PR TITLE
Add `__all__` for plugins sub-package

### PR DESCRIPTION
**Pull request by kirillzhosul**
Introduce `__all__` to specify list of plugins for linters and etc...

### CODE REVIEW

**Comment by hhamana** [comment]
LGTM, thank you!

**Comment by tomwojcik** [comment]
Hi. LGTM. Please fix black formatting. More details in the CI.

**Comment by kirillzhosul** [comment]
> Hi. LGTM. Please fix black formatting. More details in the CI.

Done 👍🏻

(Actually IDK why my editor does not format on save this time)

**Comment by tomwojcik** [comment]
Thanks!

**Pull request merged**
