### PR TITLE
`starlette_context` context manager

### PR DESCRIPTION
**Pull request by hhamana**
This creates and exposes a context manager that instantiates and resets the Token.

This isn't much actual code, it may look like it only slightly improves the code reuse of the token initialization/reset code,
but exposing it while abstracting the internal details allows 2 more important use cases:
- within unit tests, creating a mock environment to test a portion using the `context` out of a request-response cycle (helping for #46).
- leveraging FastAPI framework Depends() to allow required/optional headers to be visibly documented, plus use the full scope of FastAPI features (such as easy access to the request's body within a Depends system, (as #50 shown might be a use case).

This also introduces the first explicit support of FastAPI, which, while limited, may attract more attention to the library.

### CODE REVIEW

**Comment by hhamana** [comment]
I am particularly unsure of the naming to use for this one, as this really starts to mix many meanings of `context`. 
This might get confusing.

starlette_context: the library
starlette_context: the context manager
context: the ContextVar

**Comment by tomwojcik** [comment]
Great idea :) 

I don't like it mentiones FastAPI so much as FastAPI depends on Starlette, not the other way around, but I guess it is what it is as FastAPI is much more popular. The truth is `starlette-context` should be compatible with all ASGI frameworks. I know not all of them use dependency injection, but it's also not something that belongs exclusively to FastAPI.

I forgot about my previous PR. If you have some time, please review it. Then we can merge it as I believe you will have a few minor conflicts. 

Overall LGTM. I'm also not a fan of `starlette_context` name. Maybe `starlette_context_manager` instead? That's the only variable name that is not 100% clear, I think. It still wouldn't be obvious what it is/does, but IMHO would slightly improve readability.

**Comment by hhamana** [comment]
`starlette_context_manager` was actually my first attempt, but it just felt too literal, guided by the implementation instead of the usage, so removed the "manager". 
how about a case change? `with StarletteContext(d):`  (I can't find any agreed convention for context manager casing...)
OOP patterns? `with context_factory(d):` / `context_maker`
keep it short? `with ctx(d)`
or also  `with context_cycle(d):`

**Comment by tomwojcik** [comment]
I think `starlette_context` is too ambiguous as it shadows the name of the library. Also, we should distinguish the `context` variable which allows us to access the data, from the context within the request-response cycle. I'd aim for something as explicit as possible. WDYT about `initialize_asgi_context_cycle` ?

**Review by tomwojcik — CHANGES_REQUESTED** [review]
Let's come up with a better name for the `starlette_context` context manager.

**Comment by hhamana** [comment]
> I think `starlette_context` is too ambiguous as it shadows the name of the library. 
While technically python itself is fine with that kind of eponymous objects, some people might get confused. It also makes it feel like it's the main point of the library, which would be misleading indeed.
> WDYT about `initialize_asgi_context_cycle` or `asgi_context_cycle` ?
I do like the explicit reference to the request `cycle`, as that has been the most noticeable exception one can get here.
why the `asgi` though? while related as part of the request, it doesn't have that much to do with the protocol. this won't start a new server or request handler.
How about `with request_cycle_context`?

**Comment by tomwojcik** [comment]
> why the `asgi` though? 

Actually this library should be called `asgi-context`, not `starlette-context`, because it will work with all asgi-based frameworks. But you're right, I think `ContextVar` can be used even with asyncio without asgi, so it'd make a bad name.

> How about `with request_cycle_context`?

Sounds good :)

**Review by tomwojcik — APPROVED** [review]

**Pull request merged**
